controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
secret:
    path: /v1/secret/{hash}
    controller: App\Controller\SecretController::getSecret
    methods:    GET|HEAD
postsecret:
    path: /v1/secret/
    controller: App\Controller\SecretController::postSecret
    methods:    POST